apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: patrickmoran-cert
spec:
  secretName: patrickmoran-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: patrick-moran.com
  dnsNames:
  - patrick-moran.com
  - '*.patrick-moran.com'